version: '3.5'
services:
    crawler:
        image: synpatic/browsertrix-crawler:latest
        build:
          context: ./
        platform: linux/amd64
        cap_add:
          - NET_ADMIN
          - SYS_ADMIN
        ports:
          - "3000:3000"
        shm_size: 1gb
